// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(fold_clientFFI)
import fold_clientFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_fold_client_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_fold_client_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt32: FfiConverterPrimitive {
    typealias FfiType = Int32
    typealias SwiftType = Int32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int32, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




public protocol FoldClientProtocol : AnyObject {
    
    func cancelStream(agentId: String) 
    
    func checkHealth() throws 
    
    func clearUnread(agentId: String) 
    
    func getAgent(agentId: String)  -> Agent?
    
    func getAgents()  -> [Agent]
    
    func getMessages(agentId: String)  -> [Message]
    
    func getQueueCount(agentId: String)  -> UInt32
    
    func getSessionUsage()  -> UsageInfo
    
    func getStreamBuffer(agentId: String)  -> String
    
    func getUnread(agentId: String)  -> UInt32
    
    func isStreaming(agentId: String)  -> Bool
    
    func loadHistory(agentId: String) throws  -> [Message]
    
    func refreshAgents() throws  -> [Agent]
    
    func sendMessage(agentId: String, content: String) throws 
    
    func setStateCallback(callback: StateCallback) 
    
    func setStreamCallback(callback: StreamCallback) 
    
}

open class FoldClient:
    FoldClientProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_fold_client_fn_clone_foldclient(self.pointer, $0) }
    }
public convenience init(gatewayUrl: String) {
    let pointer =
        try! rustCall() {
    uniffi_fold_client_fn_constructor_foldclient_new(
        FfiConverterString.lower(gatewayUrl),$0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_fold_client_fn_free_foldclient(pointer, $0) }
    }

    

    
open func cancelStream(agentId: String) {try! rustCall() {
    uniffi_fold_client_fn_method_foldclient_cancel_stream(self.uniffiClonePointer(),
        FfiConverterString.lower(agentId),$0
    )
}
}
    
open func checkHealth()throws  {try rustCallWithError(FfiConverterTypeFoldError.lift) {
    uniffi_fold_client_fn_method_foldclient_check_health(self.uniffiClonePointer(),$0
    )
}
}
    
open func clearUnread(agentId: String) {try! rustCall() {
    uniffi_fold_client_fn_method_foldclient_clear_unread(self.uniffiClonePointer(),
        FfiConverterString.lower(agentId),$0
    )
}
}
    
open func getAgent(agentId: String) -> Agent? {
    return try!  FfiConverterOptionTypeAgent.lift(try! rustCall() {
    uniffi_fold_client_fn_method_foldclient_get_agent(self.uniffiClonePointer(),
        FfiConverterString.lower(agentId),$0
    )
})
}
    
open func getAgents() -> [Agent] {
    return try!  FfiConverterSequenceTypeAgent.lift(try! rustCall() {
    uniffi_fold_client_fn_method_foldclient_get_agents(self.uniffiClonePointer(),$0
    )
})
}
    
open func getMessages(agentId: String) -> [Message] {
    return try!  FfiConverterSequenceTypeMessage.lift(try! rustCall() {
    uniffi_fold_client_fn_method_foldclient_get_messages(self.uniffiClonePointer(),
        FfiConverterString.lower(agentId),$0
    )
})
}
    
open func getQueueCount(agentId: String) -> UInt32 {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_fold_client_fn_method_foldclient_get_queue_count(self.uniffiClonePointer(),
        FfiConverterString.lower(agentId),$0
    )
})
}
    
open func getSessionUsage() -> UsageInfo {
    return try!  FfiConverterTypeUsageInfo.lift(try! rustCall() {
    uniffi_fold_client_fn_method_foldclient_get_session_usage(self.uniffiClonePointer(),$0
    )
})
}
    
open func getStreamBuffer(agentId: String) -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_fold_client_fn_method_foldclient_get_stream_buffer(self.uniffiClonePointer(),
        FfiConverterString.lower(agentId),$0
    )
})
}
    
open func getUnread(agentId: String) -> UInt32 {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_fold_client_fn_method_foldclient_get_unread(self.uniffiClonePointer(),
        FfiConverterString.lower(agentId),$0
    )
})
}
    
open func isStreaming(agentId: String) -> Bool {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_fold_client_fn_method_foldclient_is_streaming(self.uniffiClonePointer(),
        FfiConverterString.lower(agentId),$0
    )
})
}
    
open func loadHistory(agentId: String)throws  -> [Message] {
    return try  FfiConverterSequenceTypeMessage.lift(try rustCallWithError(FfiConverterTypeFoldError.lift) {
    uniffi_fold_client_fn_method_foldclient_load_history(self.uniffiClonePointer(),
        FfiConverterString.lower(agentId),$0
    )
})
}
    
open func refreshAgents()throws  -> [Agent] {
    return try  FfiConverterSequenceTypeAgent.lift(try rustCallWithError(FfiConverterTypeFoldError.lift) {
    uniffi_fold_client_fn_method_foldclient_refresh_agents(self.uniffiClonePointer(),$0
    )
})
}
    
open func sendMessage(agentId: String, content: String)throws  {try rustCallWithError(FfiConverterTypeFoldError.lift) {
    uniffi_fold_client_fn_method_foldclient_send_message(self.uniffiClonePointer(),
        FfiConverterString.lower(agentId),
        FfiConverterString.lower(content),$0
    )
}
}
    
open func setStateCallback(callback: StateCallback) {try! rustCall() {
    uniffi_fold_client_fn_method_foldclient_set_state_callback(self.uniffiClonePointer(),
        FfiConverterCallbackInterfaceStateCallback.lower(callback),$0
    )
}
}
    
open func setStreamCallback(callback: StreamCallback) {try! rustCall() {
    uniffi_fold_client_fn_method_foldclient_set_stream_callback(self.uniffiClonePointer(),
        FfiConverterCallbackInterfaceStreamCallback.lower(callback),$0
    )
}
}
    

}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFoldClient: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = FoldClient

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> FoldClient {
        return FoldClient(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: FoldClient) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FoldClient {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: FoldClient, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFoldClient_lift(_ pointer: UnsafeMutableRawPointer) throws -> FoldClient {
    return try FfiConverterTypeFoldClient.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFoldClient_lower(_ value: FoldClient) -> UnsafeMutableRawPointer {
    return FfiConverterTypeFoldClient.lower(value)
}


public struct Agent {
    public var id: String
    public var name: String
    public var backend: String
    public var workingDir: String
    public var connected: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, name: String, backend: String, workingDir: String, connected: Bool) {
        self.id = id
        self.name = name
        self.backend = backend
        self.workingDir = workingDir
        self.connected = connected
    }
}



extension Agent: Equatable, Hashable {
    public static func ==(lhs: Agent, rhs: Agent) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.name != rhs.name {
            return false
        }
        if lhs.backend != rhs.backend {
            return false
        }
        if lhs.workingDir != rhs.workingDir {
            return false
        }
        if lhs.connected != rhs.connected {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(name)
        hasher.combine(backend)
        hasher.combine(workingDir)
        hasher.combine(connected)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAgent: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Agent {
        return
            try Agent(
                id: FfiConverterString.read(from: &buf), 
                name: FfiConverterString.read(from: &buf), 
                backend: FfiConverterString.read(from: &buf), 
                workingDir: FfiConverterString.read(from: &buf), 
                connected: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: Agent, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterString.write(value.backend, into: &buf)
        FfiConverterString.write(value.workingDir, into: &buf)
        FfiConverterBool.write(value.connected, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAgent_lift(_ buf: RustBuffer) throws -> Agent {
    return try FfiConverterTypeAgent.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAgent_lower(_ value: Agent) -> RustBuffer {
    return FfiConverterTypeAgent.lower(value)
}


public struct Message {
    public var id: String
    public var sender: String
    public var content: String
    public var timestamp: Int64
    public var isUser: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, sender: String, content: String, timestamp: Int64, isUser: Bool) {
        self.id = id
        self.sender = sender
        self.content = content
        self.timestamp = timestamp
        self.isUser = isUser
    }
}



extension Message: Equatable, Hashable {
    public static func ==(lhs: Message, rhs: Message) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.sender != rhs.sender {
            return false
        }
        if lhs.content != rhs.content {
            return false
        }
        if lhs.timestamp != rhs.timestamp {
            return false
        }
        if lhs.isUser != rhs.isUser {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(sender)
        hasher.combine(content)
        hasher.combine(timestamp)
        hasher.combine(isUser)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMessage: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Message {
        return
            try Message(
                id: FfiConverterString.read(from: &buf), 
                sender: FfiConverterString.read(from: &buf), 
                content: FfiConverterString.read(from: &buf), 
                timestamp: FfiConverterInt64.read(from: &buf), 
                isUser: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: Message, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.sender, into: &buf)
        FfiConverterString.write(value.content, into: &buf)
        FfiConverterInt64.write(value.timestamp, into: &buf)
        FfiConverterBool.write(value.isUser, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMessage_lift(_ buf: RustBuffer) throws -> Message {
    return try FfiConverterTypeMessage.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMessage_lower(_ value: Message) -> RustBuffer {
    return FfiConverterTypeMessage.lower(value)
}


public struct UsageInfo {
    public var inputTokens: Int32
    public var outputTokens: Int32
    public var cacheReadTokens: Int32
    public var cacheWriteTokens: Int32
    public var thinkingTokens: Int32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(inputTokens: Int32, outputTokens: Int32, cacheReadTokens: Int32, cacheWriteTokens: Int32, thinkingTokens: Int32) {
        self.inputTokens = inputTokens
        self.outputTokens = outputTokens
        self.cacheReadTokens = cacheReadTokens
        self.cacheWriteTokens = cacheWriteTokens
        self.thinkingTokens = thinkingTokens
    }
}



extension UsageInfo: Equatable, Hashable {
    public static func ==(lhs: UsageInfo, rhs: UsageInfo) -> Bool {
        if lhs.inputTokens != rhs.inputTokens {
            return false
        }
        if lhs.outputTokens != rhs.outputTokens {
            return false
        }
        if lhs.cacheReadTokens != rhs.cacheReadTokens {
            return false
        }
        if lhs.cacheWriteTokens != rhs.cacheWriteTokens {
            return false
        }
        if lhs.thinkingTokens != rhs.thinkingTokens {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(inputTokens)
        hasher.combine(outputTokens)
        hasher.combine(cacheReadTokens)
        hasher.combine(cacheWriteTokens)
        hasher.combine(thinkingTokens)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeUsageInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UsageInfo {
        return
            try UsageInfo(
                inputTokens: FfiConverterInt32.read(from: &buf), 
                outputTokens: FfiConverterInt32.read(from: &buf), 
                cacheReadTokens: FfiConverterInt32.read(from: &buf), 
                cacheWriteTokens: FfiConverterInt32.read(from: &buf), 
                thinkingTokens: FfiConverterInt32.read(from: &buf)
        )
    }

    public static func write(_ value: UsageInfo, into buf: inout [UInt8]) {
        FfiConverterInt32.write(value.inputTokens, into: &buf)
        FfiConverterInt32.write(value.outputTokens, into: &buf)
        FfiConverterInt32.write(value.cacheReadTokens, into: &buf)
        FfiConverterInt32.write(value.cacheWriteTokens, into: &buf)
        FfiConverterInt32.write(value.thinkingTokens, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeUsageInfo_lift(_ buf: RustBuffer) throws -> UsageInfo {
    return try FfiConverterTypeUsageInfo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeUsageInfo_lower(_ value: UsageInfo) -> RustBuffer {
    return FfiConverterTypeUsageInfo.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum ConnectionStatus {
    
    case connecting
    case connected
    case disconnected
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeConnectionStatus: FfiConverterRustBuffer {
    typealias SwiftType = ConnectionStatus

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ConnectionStatus {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .connecting
        
        case 2: return .connected
        
        case 3: return .disconnected
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: ConnectionStatus, into buf: inout [UInt8]) {
        switch value {
        
        
        case .connecting:
            writeInt(&buf, Int32(1))
        
        
        case .connected:
            writeInt(&buf, Int32(2))
        
        
        case .disconnected:
            writeInt(&buf, Int32(3))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConnectionStatus_lift(_ buf: RustBuffer) throws -> ConnectionStatus {
    return try FfiConverterTypeConnectionStatus.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConnectionStatus_lower(_ value: ConnectionStatus) -> RustBuffer {
    return FfiConverterTypeConnectionStatus.lower(value)
}



extension ConnectionStatus: Equatable, Hashable {}




public enum FoldError {

    
    
    case Connection(message: String)
    
    case Api(message: String)
    
    case Stream(message: String)
    
    case AgentNotFound(message: String)
    
    case AlreadyStreaming(message: String)
    
    case InvalidResponse(message: String)
    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFoldError: FfiConverterRustBuffer {
    typealias SwiftType = FoldError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FoldError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Connection(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .Api(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 3: return .Stream(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 4: return .AgentNotFound(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 5: return .AlreadyStreaming(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 6: return .InvalidResponse(
            message: try FfiConverterString.read(from: &buf)
        )
        

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FoldError, into buf: inout [UInt8]) {
        switch value {

        

        
        case .Connection(_ /* message is ignored*/):
            writeInt(&buf, Int32(1))
        case .Api(_ /* message is ignored*/):
            writeInt(&buf, Int32(2))
        case .Stream(_ /* message is ignored*/):
            writeInt(&buf, Int32(3))
        case .AgentNotFound(_ /* message is ignored*/):
            writeInt(&buf, Int32(4))
        case .AlreadyStreaming(_ /* message is ignored*/):
            writeInt(&buf, Int32(5))
        case .InvalidResponse(_ /* message is ignored*/):
            writeInt(&buf, Int32(6))

        
        }
    }
}


extension FoldError: Equatable, Hashable {}

extension FoldError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum StreamEvent {
    
    case text(content: String
    )
    case thinking(content: String
    )
    case toolUse(name: String, input: String
    )
    case toolResult(toolId: String, result: String
    )
    case toolState(state: String, detail: String
    )
    case usage(info: UsageInfo
    )
    case done
    case error(message: String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeStreamEvent: FfiConverterRustBuffer {
    typealias SwiftType = StreamEvent

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> StreamEvent {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .text(content: try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .thinking(content: try FfiConverterString.read(from: &buf)
        )
        
        case 3: return .toolUse(name: try FfiConverterString.read(from: &buf), input: try FfiConverterString.read(from: &buf)
        )
        
        case 4: return .toolResult(toolId: try FfiConverterString.read(from: &buf), result: try FfiConverterString.read(from: &buf)
        )
        
        case 5: return .toolState(state: try FfiConverterString.read(from: &buf), detail: try FfiConverterString.read(from: &buf)
        )
        
        case 6: return .usage(info: try FfiConverterTypeUsageInfo.read(from: &buf)
        )
        
        case 7: return .done
        
        case 8: return .error(message: try FfiConverterString.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: StreamEvent, into buf: inout [UInt8]) {
        switch value {
        
        
        case let .text(content):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(content, into: &buf)
            
        
        case let .thinking(content):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(content, into: &buf)
            
        
        case let .toolUse(name,input):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(name, into: &buf)
            FfiConverterString.write(input, into: &buf)
            
        
        case let .toolResult(toolId,result):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(toolId, into: &buf)
            FfiConverterString.write(result, into: &buf)
            
        
        case let .toolState(state,detail):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(state, into: &buf)
            FfiConverterString.write(detail, into: &buf)
            
        
        case let .usage(info):
            writeInt(&buf, Int32(6))
            FfiConverterTypeUsageInfo.write(info, into: &buf)
            
        
        case .done:
            writeInt(&buf, Int32(7))
        
        
        case let .error(message):
            writeInt(&buf, Int32(8))
            FfiConverterString.write(message, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeStreamEvent_lift(_ buf: RustBuffer) throws -> StreamEvent {
    return try FfiConverterTypeStreamEvent.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeStreamEvent_lower(_ value: StreamEvent) -> RustBuffer {
    return FfiConverterTypeStreamEvent.lower(value)
}



extension StreamEvent: Equatable, Hashable {}






public protocol StateCallback : AnyObject {
    
    func onConnectionStatus(status: ConnectionStatus) 
    
    func onMessagesChanged(agentId: String) 
    
    func onQueueChanged(agentId: String, count: UInt32) 
    
    func onUnreadChanged(agentId: String, count: UInt32) 
    
    func onStreamingChanged(agentId: String, isStreaming: Bool) 
    
}

// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceStateCallback {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    static var vtable: UniffiVTableCallbackInterfaceStateCallback = UniffiVTableCallbackInterfaceStateCallback(
        onConnectionStatus: { (
            uniffiHandle: UInt64,
            status: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceStateCallback.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onConnectionStatus(
                     status: try FfiConverterTypeConnectionStatus.lift(status)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onMessagesChanged: { (
            uniffiHandle: UInt64,
            agentId: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceStateCallback.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onMessagesChanged(
                     agentId: try FfiConverterString.lift(agentId)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onQueueChanged: { (
            uniffiHandle: UInt64,
            agentId: RustBuffer,
            count: UInt32,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceStateCallback.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onQueueChanged(
                     agentId: try FfiConverterString.lift(agentId),
                     count: try FfiConverterUInt32.lift(count)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onUnreadChanged: { (
            uniffiHandle: UInt64,
            agentId: RustBuffer,
            count: UInt32,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceStateCallback.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onUnreadChanged(
                     agentId: try FfiConverterString.lift(agentId),
                     count: try FfiConverterUInt32.lift(count)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onStreamingChanged: { (
            uniffiHandle: UInt64,
            agentId: RustBuffer,
            isStreaming: Int8,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceStateCallback.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onStreamingChanged(
                     agentId: try FfiConverterString.lift(agentId),
                     isStreaming: try FfiConverterBool.lift(isStreaming)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            let result = try? FfiConverterCallbackInterfaceStateCallback.handleMap.remove(handle: uniffiHandle)
            if result == nil {
                print("Uniffi callback interface StateCallback: handle missing in uniffiFree")
            }
        }
    )
}

private func uniffiCallbackInitStateCallback() {
    uniffi_fold_client_fn_init_callback_vtable_statecallback(&UniffiCallbackInterfaceStateCallback.vtable)
}

// FfiConverter protocol for callback interfaces
#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterCallbackInterfaceStateCallback {
    fileprivate static var handleMap = UniffiHandleMap<StateCallback>()
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
extension FfiConverterCallbackInterfaceStateCallback : FfiConverter {
    typealias SwiftType = StateCallback
    typealias FfiType = UInt64

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ handle: UInt64) throws -> SwiftType {
        try handleMap.get(handle: handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ v: SwiftType) -> UInt64 {
        return handleMap.insert(obj: v)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(v))
    }
}




public protocol StreamCallback : AnyObject {
    
    func onEvent(agentId: String, event: StreamEvent) 
    
}



// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceStreamCallback {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    static var vtable: UniffiVTableCallbackInterfaceStreamCallback = UniffiVTableCallbackInterfaceStreamCallback(
        onEvent: { (
            uniffiHandle: UInt64,
            agentId: RustBuffer,
            event: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceStreamCallback.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onEvent(
                     agentId: try FfiConverterString.lift(agentId),
                     event: try FfiConverterTypeStreamEvent.lift(event)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            let result = try? FfiConverterCallbackInterfaceStreamCallback.handleMap.remove(handle: uniffiHandle)
            if result == nil {
                print("Uniffi callback interface StreamCallback: handle missing in uniffiFree")
            }
        }
    )
}

private func uniffiCallbackInitStreamCallback() {
    uniffi_fold_client_fn_init_callback_vtable_streamcallback(&UniffiCallbackInterfaceStreamCallback.vtable)
}

// FfiConverter protocol for callback interfaces
#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterCallbackInterfaceStreamCallback {
    fileprivate static var handleMap = UniffiHandleMap<StreamCallback>()
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
extension FfiConverterCallbackInterfaceStreamCallback : FfiConverter {
    typealias SwiftType = StreamCallback
    typealias FfiType = UInt64

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ handle: UInt64) throws -> SwiftType {
        try handleMap.get(handle: handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ v: SwiftType) -> UInt64 {
        return handleMap.insert(obj: v)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(v))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeAgent: FfiConverterRustBuffer {
    typealias SwiftType = Agent?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeAgent.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeAgent.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeAgent: FfiConverterRustBuffer {
    typealias SwiftType = [Agent]

    public static func write(_ value: [Agent], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeAgent.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Agent] {
        let len: Int32 = try readInt(&buf)
        var seq = [Agent]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeAgent.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeMessage: FfiConverterRustBuffer {
    typealias SwiftType = [Message]

    public static func write(_ value: [Message], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeMessage.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Message] {
        let len: Int32 = try readInt(&buf)
        var seq = [Message]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeMessage.read(from: &buf))
        }
        return seq
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_fold_client_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_fold_client_checksum_method_foldclient_cancel_stream() != 7243) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fold_client_checksum_method_foldclient_check_health() != 32522) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fold_client_checksum_method_foldclient_clear_unread() != 52201) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fold_client_checksum_method_foldclient_get_agent() != 46852) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fold_client_checksum_method_foldclient_get_agents() != 45232) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fold_client_checksum_method_foldclient_get_messages() != 5329) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fold_client_checksum_method_foldclient_get_queue_count() != 28554) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fold_client_checksum_method_foldclient_get_session_usage() != 52729) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fold_client_checksum_method_foldclient_get_stream_buffer() != 15787) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fold_client_checksum_method_foldclient_get_unread() != 12191) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fold_client_checksum_method_foldclient_is_streaming() != 46350) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fold_client_checksum_method_foldclient_load_history() != 6985) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fold_client_checksum_method_foldclient_refresh_agents() != 8969) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fold_client_checksum_method_foldclient_send_message() != 41070) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fold_client_checksum_method_foldclient_set_state_callback() != 33340) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fold_client_checksum_method_foldclient_set_stream_callback() != 1197) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fold_client_checksum_constructor_foldclient_new() != 18889) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fold_client_checksum_method_statecallback_on_connection_status() != 56576) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fold_client_checksum_method_statecallback_on_messages_changed() != 45182) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fold_client_checksum_method_statecallback_on_queue_changed() != 10197) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fold_client_checksum_method_statecallback_on_unread_changed() != 57620) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fold_client_checksum_method_statecallback_on_streaming_changed() != 30236) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fold_client_checksum_method_streamcallback_on_event() != 26457) {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiCallbackInitStateCallback()
    uniffiCallbackInitStreamCallback()
    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all